// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/proto/seckill.proto

package seckill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 秒杀请求
type SeckillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`     // 用户名
	GoodsId       int64                  `protobuf:"varint,2,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"` // 商品ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillRequest) Reset() {
	*x = SeckillRequest{}
	mi := &file_api_proto_seckill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillRequest) ProtoMessage() {}

func (x *SeckillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_seckill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillRequest.ProtoReflect.Descriptor instead.
func (*SeckillRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_seckill_proto_rawDescGZIP(), []int{0}
}

func (x *SeckillRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SeckillRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

// 秒杀响应
type SeckillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                     // 状态码: 0-成功, 1-库存不足, 2-重复秒杀, 3-系统错误
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                // 提示信息
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单ID (成功时返回)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillResponse) Reset() {
	*x = SeckillResponse{}
	mi := &file_api_proto_seckill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillResponse) ProtoMessage() {}

func (x *SeckillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_seckill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillResponse.ProtoReflect.Descriptor instead.
func (*SeckillResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_seckill_proto_rawDescGZIP(), []int{1}
}

func (x *SeckillResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SeckillResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SeckillResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// 结果查询请求
type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`     // 用户名
	GoodsId       int64                  `protobuf:"varint,2,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"` // 商品ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_api_proto_seckill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_seckill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_seckill_proto_rawDescGZIP(), []int{2}
}

func (x *ResultRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResultRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

// 结果查询响应
type ResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // -1: 排队中, 0: 秒杀成功, 1: 秒杀失败
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_api_proto_seckill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_seckill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_seckill_proto_rawDescGZIP(), []int{3}
}

func (x *ResultResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ResultResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_api_proto_seckill_proto protoreflect.FileDescriptor

const file_api_proto_seckill_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/seckill.proto\x12\aseckill\"D\n" +
	"\x0eSeckillRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bgoods_id\x18\x02 \x01(\x03R\agoodsId\"Z\n" +
	"\x0fSeckillResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"C\n" +
	"\rResultRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bgoods_id\x18\x02 \x01(\x03R\agoodsId\"C\n" +
	"\x0eResultResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId2\x95\x01\n" +
	"\x0eSeckillService\x12>\n" +
	"\tDoSeckill\x12\x17.seckill.SeckillRequest\x1a\x18.seckill.SeckillResponse\x12C\n" +
	"\x10GetSeckillResult\x12\x16.seckill.ResultRequest\x1a\x17.seckill.ResultResponseB\vZ\t./seckillb\x06proto3"

var (
	file_api_proto_seckill_proto_rawDescOnce sync.Once
	file_api_proto_seckill_proto_rawDescData []byte
)

func file_api_proto_seckill_proto_rawDescGZIP() []byte {
	file_api_proto_seckill_proto_rawDescOnce.Do(func() {
		file_api_proto_seckill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_seckill_proto_rawDesc), len(file_api_proto_seckill_proto_rawDesc)))
	})
	return file_api_proto_seckill_proto_rawDescData
}

var file_api_proto_seckill_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_seckill_proto_goTypes = []any{
	(*SeckillRequest)(nil),  // 0: seckill.SeckillRequest
	(*SeckillResponse)(nil), // 1: seckill.SeckillResponse
	(*ResultRequest)(nil),   // 2: seckill.ResultRequest
	(*ResultResponse)(nil),  // 3: seckill.ResultResponse
}
var file_api_proto_seckill_proto_depIdxs = []int32{
	0, // 0: seckill.SeckillService.DoSeckill:input_type -> seckill.SeckillRequest
	2, // 1: seckill.SeckillService.GetSeckillResult:input_type -> seckill.ResultRequest
	1, // 2: seckill.SeckillService.DoSeckill:output_type -> seckill.SeckillResponse
	3, // 3: seckill.SeckillService.GetSeckillResult:output_type -> seckill.ResultResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_seckill_proto_init() }
func file_api_proto_seckill_proto_init() {
	if File_api_proto_seckill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_seckill_proto_rawDesc), len(file_api_proto_seckill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_seckill_proto_goTypes,
		DependencyIndexes: file_api_proto_seckill_proto_depIdxs,
		MessageInfos:      file_api_proto_seckill_proto_msgTypes,
	}.Build()
	File_api_proto_seckill_proto = out.File
	file_api_proto_seckill_proto_goTypes = nil
	file_api_proto_seckill_proto_depIdxs = nil
}
