brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH

# 允许自动创建 topic
autoCreateTopicEnable = true

# Broker IP 配置
brokerIP1 = 172.28.0.11

# 定时消息配置（RocketMQ 5.x）
timerWheelEnable = true
