server:
  port: 8080

mysql:
  host: mysql
  port: 3306
  database: seckill
  username: root
  password: root123
  max_open_conns: 2000
  max_idle_conns: 2000

redis:
  addr: redis:6379
  password: ""
  db: 0
  pool_size: 2000

# Kafka 配置
kafka:
  brokers:
    - kafka:9092
  topic: seckill_orders
  group: seckill_consumer_group

# 订单超时配置
timeout:
  order_timeout_seconds: 60    # 订单超时时间（秒）
  redis_scan_interval: "1s"    # Redis ZSET 扫描间隔
  mysql_scan_interval: "5m"    # MySQL 兜底扫描间隔

jwt:
  secret: "W6jP5ADwpuqVCtza1ftmxyS2cll1QDaYAM6aaWEkJyI="
  expire_hours: 24

admin:
  secret: "tdPrNHfDnVCq+cQv8YvyW01dni0KVQ8maB0QracsWN8="
